package com.example.upitracker.util

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import android.net.Uri
import androidx.core.content.ContextCompat
import androidx.core.graphics.drawable.toBitmap
import com.example.upitracker.R
import com.example.upitracker.data.Transaction
import java.io.FileOutputStream
import java.text.NumberFormat
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import androidx.core.graphics.toColorInt

object PdfGenerator {

    fun generatePassbookPdf(
        context: Context,
        transactions: List<Transaction>,
        statementPeriod: String,
        targetUri: Uri,
        showBankName: Boolean = true,
        includeCategoryBreakdown: Boolean = true
    ) {
        val document = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create()
        var page = document.startPage(pageInfo)
        var canvas: Canvas = page.canvas

        val primaryColor = "#3F51B5".toColorInt()
        val textColor = Color.BLACK

        val titlePaint = Paint().apply { textSize = 18f; isFakeBoldText = true; color = primaryColor }
        val periodPaint = Paint().apply { textSize = 12f; color = Color.GRAY }
        val headerPaint = Paint().apply { textSize = 10f; isFakeBoldText = true; color = textColor }
        val textPaint = Paint().apply { textSize = 9f; color = textColor }
        val rightAlignPaint = Paint(textPaint).apply { textAlign = Paint.Align.RIGHT }
        val tableLinePaint = Paint().apply { strokeWidth = 0.5f; color = Color.GRAY }

        val leftMargin = 40f
        val rightMargin = 555f
        val descColX = 95f
        val debitColX = 470f

        var pageCount = 1
        val footerPaint = Paint().apply { textSize = 8f; color = Color.GRAY }
        val rightAlignFooterPaint = Paint().apply { textSize = 8f; color = Color.GRAY; textAlign = Paint.Align.RIGHT }

        fun drawPageHeader(pageCanvas: Canvas) {
            ContextCompat.getDrawable(context, R.mipmap.ic_launcher_round)?.let { drawable ->
                val iconBitmap = drawable.toBitmap(width = 40, height = 40)
                pageCanvas.drawBitmap(iconBitmap, leftMargin, 40f, null)
            }
            pageCanvas.drawText("Transaction Statement", leftMargin + 55f, 60f, titlePaint)
            pageCanvas.drawText(statementPeriod, leftMargin + 55f, 80f, periodPaint)

            pageCanvas.drawText("Date", leftMargin, 120f, headerPaint)
            pageCanvas.drawText("Description", descColX, 120f, headerPaint)
            pageCanvas.drawText("Debit", debitColX, 120f, rightAlignPaint)
            pageCanvas.drawText("Credit", rightMargin, 120f, rightAlignPaint)
            pageCanvas.drawLine(leftMargin, 128f, rightMargin, 128f, tableLinePaint)
        }

        fun drawPageFooter(pageCanvas: Canvas, pageNum: Int) {
            pageCanvas.drawLine(leftMargin, 810f, rightMargin, 810f, tableLinePaint)
            pageCanvas.drawText("Generated by UPI Tracker", leftMargin, 822f, footerPaint)
            pageCanvas.drawText("Page $pageNum", rightMargin, 822f, rightAlignFooterPaint)
        }

        drawPageHeader(canvas)
        var yPosition = 145f

        val currencyFormatter = NumberFormat.getCurrencyInstance(Locale.Builder().setLanguage("en").setRegion("IN").build())
        val dateFormat = SimpleDateFormat("dd-MM-yyyy", Locale.getDefault())

        for (txn in transactions) {
            val rawDesc = txn.description
            val displayDesc = if (showBankName && !txn.bankName.isNullOrBlank()) {
                "[${txn.bankName}] $rawDesc"
            } else {
                rawDesc
            }
            val descriptionLines = splitText(displayDesc, 290f, textPaint)
            val rowHeight = (descriptionLines.size * 12f) + 8f

            if (yPosition + rowHeight > 800) {
                drawPageFooter(canvas, pageCount)
                document.finishPage(page)
                pageCount++
                page = document.startPage(pageInfo)
                canvas = page.canvas
                drawPageHeader(canvas)
                yPosition = 145f
            }

            val rowTopY = yPosition
            canvas.drawText(dateFormat.format(Date(txn.date)), leftMargin, rowTopY, textPaint)

            var descY = rowTopY
            descriptionLines.forEach { line ->
                canvas.drawText(line, descColX, descY, textPaint)
                descY += 12f
            }

            if (txn.type.equals("DEBIT", true)) {
                canvas.drawText(currencyFormatter.format(txn.amount), debitColX, rowTopY, rightAlignPaint)
            } else {
                canvas.drawText(currencyFormatter.format(txn.amount),
                    rightMargin, rowTopY, rightAlignPaint)
            }

            yPosition = maxOf(yPosition + 12, descY + 8)
            canvas.drawLine(leftMargin, yPosition, rightMargin, yPosition, tableLinePaint)
            yPosition += 12
        }

        // Calculate and draw total sums of debits and credits at the end
        val totalDebit = transactions.filter { it.type.equals("DEBIT", true) }.sumOf { it.amountPaise }.toMajorUnits()
        val totalCredit = transactions.filter { it.type.equals("CREDIT", true) }.sumOf { it.amountPaise }.toMajorUnits()

        val summaryHeight = 35f
        if (yPosition + summaryHeight > 800) {
            drawPageFooter(canvas, pageCount)
            document.finishPage(page)
            pageCount++
            page = document.startPage(pageInfo)
            canvas = page.canvas
            drawPageHeader(canvas)
            yPosition = 145f
        }

        // Bold text paints for the totals summary row
        val boldHeaderPaint = Paint().apply { textSize = 10f; isFakeBoldText = true; color = textColor }
        val boldRightAlignPaint = Paint(boldHeaderPaint).apply { textAlign = Paint.Align.RIGHT }

        // Draw double line or bold line above totals
        canvas.drawLine(leftMargin, yPosition, rightMargin, yPosition, tableLinePaint)
        yPosition += 15f
        
        canvas.drawText("Total Summary", descColX, yPosition, boldHeaderPaint)
        canvas.drawText(currencyFormatter.format(totalDebit), debitColX, yPosition, boldRightAlignPaint)
        canvas.drawText(currencyFormatter.format(totalCredit),
            rightMargin, yPosition, boldRightAlignPaint)

        yPosition += 8f
        canvas.drawLine(leftMargin, yPosition, rightMargin, yPosition, tableLinePaint)
        canvas.drawLine(leftMargin, yPosition + 2f, rightMargin, yPosition + 2f, tableLinePaint)

        // Draw Category breakdown if requested
        val categoryBreakdown = if (includeCategoryBreakdown) {
            transactions
                .filter { it.category != null }
                .groupBy { it.category!! }
                .mapValues { (_, txns) -> txns.sumOf { it.amountPaise }.toMajorUnits() }
                .toList()
                .sortedByDescending { it.second }
        } else {
            emptyList()
        }

        if (includeCategoryBreakdown && categoryBreakdown.isNotEmpty()) {
            val breakHeight = 45f
            if (yPosition + breakHeight > 800) {
                drawPageFooter(canvas, pageCount)
                document.finishPage(page)
                pageCount++
                page = document.startPage(pageInfo)
                canvas = page.canvas
                drawPageHeader(canvas)
                yPosition = 145f
            }

            yPosition += 25f
            canvas.drawText("Category Spending Breakdown", leftMargin, yPosition, boldHeaderPaint)
            yPosition += 10f
            canvas.drawLine(leftMargin, yPosition, rightMargin, yPosition, tableLinePaint)
            yPosition += 15f

            for ((category, amount) in categoryBreakdown) {
                if (yPosition + 20f > 800) {
                    drawPageFooter(canvas, pageCount)
                    document.finishPage(page)
                    pageCount++
                    page = document.startPage(pageInfo)
                    canvas = page.canvas
                    drawPageHeader(canvas)
                    yPosition = 145f
                    canvas.drawLine(leftMargin, yPosition, rightMargin, yPosition, tableLinePaint)
                    yPosition += 15f
                }

                canvas.drawText(category, descColX, yPosition, textPaint)
                canvas.drawText(currencyFormatter.format(amount),
                    rightMargin, yPosition, rightAlignPaint)
                yPosition += 15f
            }
            canvas.drawLine(leftMargin, yPosition, rightMargin, yPosition, tableLinePaint)
        }

        drawPageFooter(canvas, pageCount)
        document.finishPage(page)

        try {
            context.contentResolver.openFileDescriptor(targetUri, "w")?.use {
                FileOutputStream(it.fileDescriptor).use { outputStream ->
                    document.writeTo(outputStream)
                }
            }
        } finally {
            document.close()
        }
    }

    private fun splitText(text: String, maxWidth: Float, paint: Paint): List<String> {
        val lines = mutableListOf<String>()
        var start = 0
        while (start < text.length) {
            val count = paint.breakText(text, start, text.length, true, maxWidth, null)
            lines.add(text.substring(start, start + count))
            start += count
        }
        return lines
    }
}
